version: "3.8"

services:
  app:
    build: .
    container_name: express-upload-app
    ports:
      - "6969:6969"
    volumes:
      - ./storage:/usr/src/app/storage # Mount folder storage
      - ./src:/usr/src/app/src # Mount folder src (opsional)
    environment:
      - NODE_ENV=development
    restart: unless-stopped
