version: "3.8"

services:
  uploader:
    build: ./uploader
    container_name: file-upload-api
    ports:
      - "4567:4567"
    environment:
      - PUBLIC_URL=http://localhost
    volumes:
      - files-data:/var/www/files
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx-fileserver
    ports:
      - "80:80"
    volumes:
      - files-data:/var/www/files
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

volumes:
  files-data:
